# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""Tests for where an extended key of this package meets btclib's layers.

An extended key is BIP32's format, so `bip32` is what reads one: btclib's
`curves`, `ecc` and `b58` take the scalar or the point it resolves to and
refuse the key itself (issue btclib-org/btclib#1188). btclib does not
import this package, so the refusal of this package's objects is asked
here, and the resolution through `bip32` beside it.
"""

from __future__ import annotations

import pytest
from btclib import b58
from btclib.b58 import wif_from_prv_key
from btclib.curves import bytes_from_point, mult, scalar_from_prv_key
from btclib.ecc import bms, dsa, ssa
from btclib.exceptions import BTClibTypeError, BTClibValueError
from btclib.hashes import magic_message
from btclib.key import PrvKeyData, PubKeyData

from btclib_wallet.bip32 import BIP32KeyData, bip32, rootxprv_from_seed
from btclib_wallet.mnemonic import bip39
from tests import replace_unchecked


def test_an_extended_key_is_no_scalar() -> None:
    """A WIF and an xprv reach `scalar_from_prv_key` as text, and fail as hex.

    The decoded `BIP32KeyData` is refused as a type: the scalar is what
    `bip32.prv_keyinfo_from_xprv` resolves it to.
    """
    q = 0xC0FFEE
    xprv = rootxprv_from_seed("5e" * 32)
    for text in (wif_from_prv_key(q), xprv):
        with pytest.raises(BTClibValueError, match="invalid hex string"):
            scalar_from_prv_key(text)
    with pytest.raises(BTClibTypeError, match="invalid octets type: BIP32KeyData"):
        scalar_from_prv_key(BIP32KeyData.b58decode(xprv))  # type: ignore[arg-type]
    assert scalar_from_prv_key(bip32.prv_keyinfo_from_xprv(xprv)[0]) > 0


def test_an_extended_key_is_no_bip340_key() -> None:
    """The three spellings of a public xpub, refused by `ssa`.

    `ssa` parses the spellings it takes with `curves`, whose `PubKey`
    union names no extended key, so all three are refused as octets
    rather than resolved. The key field is replaced with a point of the
    curve, so what refuses these is their being extended keys and not
    their contents.
    """
    q, _ = ssa.gen_keys()
    xpub_data = BIP32KeyData.b58decode(
        "xpub6H1LXWLaKsWFhvm6RVpEL9P4KfRZSW7abD2ttkWP3SSQvnyA8FSVqNTEcYFgJS2UaFcxupHiYkro49S8yGasTvXEYBVPamhGW6cFJodrTHy"
    )
    xpub_data = replace_unchecked(xpub_data, key=bytes_from_point(mult(q)))
    xpub = xpub_data.b58encode()

    with pytest.raises(BTClibTypeError, match="not a BIP340 public key"):
        ssa.point_from_bip340pub_key(xpub_data)
    # a `str` is read as hex and the Base58 alphabet is not hex, where the
    # same characters as `bytes` are already octets and are refused for
    # their length
    with pytest.raises(BTClibValueError, match="invalid hex string"):
        ssa.point_from_bip340pub_key(xpub)
    err_msg = r"invalid size: 111 bytes instead of \(32, 33, 65\)"
    with pytest.raises(BTClibValueError, match=err_msg):
        ssa.point_from_bip340pub_key(xpub.encode("ascii"))


@pytest.mark.parametrize(
    "derivation_path, msg, dersig_hex",
    [
        pytest.param(
            "m/1",
            b"\xfb\xa3\x1f\x8cd\x85\xe29#K\xb3{\xfd\xa7<?\x95oL\xee\x19\xb2'oh\xa7]\xd9A\xfeU\xd8",
            "3144022012ec0c174936c2a46dc657252340b2e6e6dd8c31dd059b6f9f33a90c21af2fba022030e6305b3ccf88009d419bf7651afcfcc0a30898b93ae9de9aa6ac03cf8ec56b",
            id="non-standard leading 31",
        ),
        pytest.param(
            "m/0/0",
            b"hello world",
            "3045022100967dac3262b4686e89638c8219c5761017f05cd87a855edf034f4a3ec6b59d3d0220108a4ef9682b71a45979d8c75c393382d9ccb8eb561d73b8c5fc0b87a47e7d27",
            id="standard leading 30",
        ),
    ],
)
def test_ledger(derivation_path: str, msg: bytes, dersig_hex: str) -> None:
    """Hybrid ECDSA Bitcoin message signature generated by Ledger.

    The public key is the xpub's, which `bip32` resolves: neither `dsa`
    nor `b58` reads an extended key.
    """
    mnemonic = (
        "barely sun snack this snack relief pipe attack disease boss enlist lawsuit"
    )
    xprv = bip32.derive(bip39.mxprv_from_mnemonic(mnemonic), derivation_path)
    magic_msg = magic_message(msg)

    # save the key id and patch the DER leading octet
    dersig = bytes.fromhex(dersig_hex)
    key_id = dersig[0]
    dsa_sig = dsa.Sig.parse(b"\x30" + dersig[1:])

    sec = bip32.pub_keyinfo_from_xkey(bip32.xpub_from_xprv(xprv))[0]
    dsa.assert_as_valid(magic_msg, sec, dsa_sig)
    assert dsa.verify(magic_msg, sec, dsa_sig)

    # the equivalent Bitcoin Message Signature, for the compressed address
    addr = b58.p2pkh(PubKeyData(sec))
    bms_sig = bms.Sig(27 + 4 + (key_id & 0x01), dsa_sig)
    bms.assert_as_valid(msg, addr, bms_sig)
    assert bms.verify(msg, addr, bms_sig)
    assert not bms.verify(magic_msg, addr, bms_sig)

    bms.sign(msg, PrvKeyData(*bip32.prv_keyinfo_from_xprv(xprv)))
